### ISSUE TITLE
Additional import fixes

### ISSUE THREAD

**Issue by elliotclee** [joelgraff/pivy-trackers#21]
Hi,

Here is a patch for a few more import fixes along the lines of what @HakanSeven12 did recently. I needed these in order to get the freecad.trails workbench to load in FreeCAD.

[pivy_trackers-import.patch.gz](https://github.com/joelgraff/pivy_trackers/files/4743608/pivy_trackers-import.patch.gz)

**Comment by joelgraff** [comment]
Right.  I'm trying to sort those out at the moment.  Things have gotten a bit confused.  Do you have pivy_trackers installed as a separate module?

And which branch are you pulling from?

I'm currently working on incorporating pivy_trackers into FreeCAD trails driectly, so the double reference in the name is not necessary.

Also, if you look in your FreeCAD Trails folder, is there a pivy_trackers folder inside?  If so, it may be that you haven't forced git to update the submodule, so it's still empty.

**Comment by elliotclee** [comment]
I just cloned freecad.trails out with --recursive, no branch explicitly
specified. The pivy_trackers subdirectory is there and populated.

Elliot

**Comment by joelgraff** [comment]
I've provided an interim fix which should alleviate this issue.
