### ISSUE TITLE
delete pycache file

### ISSUE THREAD

**Issue by berndhahnebach** [joelgraff/pivy-trackers#23]
Would it be possible to delete this file in the repository?

https://github.com/joelgraff/pivy_trackers/blob/032b930fe0cb8cf67071ffdf02346844b7359cfd/__pycache__/__init__.cpython-36.pyc

As soon as I am on Windows and change to trails in FreeCAD the file will be changed and git has recognised the changes. But if the file is deleted and will be created gitignore works and git does not would like me to commit changes.

bernd

**Comment by joelgraff** [comment]
Thanks for catching that.  I just removed it from the filesystem.
