### ISSUE TITLE
wiki broken

### ISSUE THREAD

**Issue by luzpaz** [joelgraff/pivy-trackers#24]
![image](https://user-images.githubusercontent.com/4140247/108097031-a18c8400-704f-11eb-8319-01f32c7dc2f7.png)

**Comment by HakanSeven12** [comment]
Works for me
![Screenshot_20210216-210022](https://user-images.githubusercontent.com/3831435/108102804-1d132300-709a-11eb-80ed-529272481f32.jpg)

**Comment by joelgraff** [comment]
A little confused by this... what works for you?

*Joel Graff, P.E.*

*LinkedIn:* https://www.linkedin.com/in/joelcgraff

**Comment by luzpaz** [comment]
weird anomaly that is now magically fixed. lol
Sorry.
