### ISSUE TITLE
Need your help in using pivy_trackers

### ISSUE THREAD

**Issue by MariwanJ** [joelgraff/pivy-trackers#25]
Hi, 
I would like to take benefit of this tool to implement my  fr_widget sets. The aim of the widgets is to make it easy to implement an interface for the direct modelling. 
I wish to take only the files I need to draw my widgets (both graphics and text). I don't make a mess of files that I don't use. 
 
You might look at my github, I have already drawing functionality with text drawing also. But you know by yourself, coin is not easy to understand as there are lack of examples. (as a beginner I say that)

What I am doing with the widget is to have the drawing and interactive interface (with some qt combination to give push-button, input widgets, some other drawing like wheel for rotation ..etc). Having the widgets implemented, will make implementation of the "direct modelling" is just about doing the real work against OpenCascad interface in FreeCAD. 
Your help will push my effort to implement the real work quicker thanks.

Due to disrespect I got on the freecad [forum](https://forum.freecadweb.org/viewtopic.php?p=496326#p496326).
I don't use the forum anymore so please use github to communicate with me. 

Thanks in advance
Mariwan (Owner of Design456 WorkBench)

**Comment by MariwanJ** [comment]
NP. I will try by myself. BR

**Comment by joelgraff** [comment]
Whether or not pivy_trackers would be useful to you is not clear.  And yes, interacting with Coin3D is a bit tricky.  If you need only limited interaction, I would recommend implementing your own solution - pivy_trackers is a rather large dependency to have to add.

that said, if you have questions about working with Coin3D, feel free to ask.

**Comment by MariwanJ** [comment]
Thanks. After looking to the code, it was  difficult to know the dependency. 
I need two things : 
1. draw (line, frame, square, primitive objects) (not so difficult for me now)
2. draw label (text) (is little bit difficult as I need to alignment function also)
I have already both and I will continue to do what else it needs. 
Widget system is easier (to understand, to use). I try to use the same simple way where FLTK GUI is made. I hope this will give a better way to interact with internal engine. 
Thanks anyway.
