### ISSUE TITLE
Access to the wiki

### ISSUE THREAD

**Issue by luzpaz** [joelgraff/pivy-trackers#6]
Cloned the wiki and made some cosmetic changes but I have no idea how to push said pages back via PR. Any idea ?

**Comment by joelgraff** [comment]
Looks a bit tricky to manage [PR's for wiki's...](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html)

However..  I think if I just add you as a collaborator, you can do what you like. :)

**Comment by luzpaz** [comment]
Thanks
